services:
  - type: web
    name: ajaia-docs-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
